version: "3.8"
services:
  zookeeper-1:
    container_name: zookeeper-1
    image: qbits/zookeeper:3.3.1
    build:
      context: ./kafka/zookeeper
    volumes:
      - ./kafka/config/zookeeper-1/zookeeper.properties:/kafka/config/zookeeper.properties
    networks:
      - wx
  kafka-1:
    container_name: kafka-1
    image: qbits/kafka:3.3.1
    build:
      context: ./kafka
    volumes:
      - ./kafka/config/kafka-1/server.properties:/kafka/config/server.properties
      - ./kafka/data/kafka-1/:/tmp/kafka-logs/
    networks:
      - wx
  kafka-producer:
    container_name: kafka-producer
    image: qbits/kafka:3.3.1
    build:
      context: .
    working_dir: /kafka
    entrypoint: /bin/bash
    stdin_open: true
    tty: true
    networks:
      - wx
  kafka-consumer:
    container_name: kafka-consumer
    image: qbits/kafka:3.3.1
    build:
      context: .
    working_dir: /kafka
    entrypoint: /bin/bash
    stdin_open: true
    tty: true
    networks:
      - wx
  service-relay:
    container_name: wx-svc-relay
    image: qbits/wx-svc-relay:0.0.5
    build:
      context: ./services/relay
    environment:
      KAFKA_TOPIC: "wxTopic"
      KAFKA_BROKERS: "kafka-1:9092,kafka-2:9092"
      STATION_URL: "http://10.20.70.10"
    networks:
      - wx
  service-influxdb:
    container_name: wx-svc-influxdb
    image: influxdb:2.7.0
    volumes:
      - ./services/influxdb/data:/var/lib/influxdb2:rw
    env_file:
      - .env
    entrypoint: ["./entrypoint.sh"]
    restart: on-failure:10
    ports:
      - ${DOCKER_INFLUXDB_INIT_PORT}:${DOCKER_INFLUXDB_INIT_PORT}
    networks:
      - wx
  service-telegraf:
    container_name: wx-svc-telegraf
    image: telegraf:1.26.1
    volumes:
      - ${TELEGRAF_CFG_PATH}:/etc/telegraf/telegraf.conf:rw
    env_file:
      - .env
    depends_on:
      - service-influxdb
    networks:
      - wx
  grafana-dashboard:
    container_name: wx-svc-dashboard
    image: grafana/grafana-enterprise
    ports:
      - 3000:3000
    volumes:
      - ./services/grafana/grafana.ini:/etc/grafana/grafana.ini
    networks:
      - wx
networks:
  wx:
    name: wx
