version: "3.8"
services:
  zookeeper-1:
    container_name: zookeeper-1
    image: qbits/zookeeper:3.3.1
    build:
      context: ./kafka/zookeeper
    volumes:
      - ./kafka/config/zookeeper-1/zookeeper.properties:/kafka/config/zookeeper.properties
    networks:
      - kafka
  kafka-1:
    container_name: kafka-1
    image: qbits/kafka:3.3.1
    build:
      context: ./kafka
    volumes:
      - ./kafka/config/kafka-1/server.properties:/kafka/config/server.properties
      - ./kafka/data/kafka-1/:/tmp/kafka-logs/
    networks:
      - kafka
  kafka-producer:
    container_name: kafka-producer
    image: qbits/kafka:3.3.1
    build:
     context: .
    working_dir: /kafka
    entrypoint: /bin/bash
    stdin_open: true
    tty: true
    networks:
    - kafka
  kafka-consumer: 
    container_name: kafka-consumer
    image: qbits/kafka:3.3.1
    build: 
      context: .
    working_dir: /kafka
    entrypoint: /bin/bash
    stdin_open: true
    tty: true
    networks:
    - kafka
  service-relay:
    container_name: wx-svc-relay
    image: qbits/wx-svc-relay:0.0.4
    build: 
      context: ./services/relay
    environment:
      KAFKA_TOPIC: "wxTopic"
      KAFKA_BROKERS: "kafka-1:9092,kafka-2:9092"
      STATION_URL: "http://10.20.70.10"
    networks:
    - kafka
networks:
  kafka:
    name: kafka