version: "3.8"
services:
  broker:
    container_name: broker
    image: apache/kafka:latest
    ports:
      - 9092:9092
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://broker:9092,CONTROLLER://broker:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 1
    restart: always
    networks:
      - wx
  service-relay:
    container_name: wx-svc-relay
    image: qbits/wx-svc-relay:0.0.5
    build:
      context: ./services/relay
    environment:
      KAFKA_TOPIC: "wxTopic"
      KAFKA_BROKERS: "broker:9092"
      STATION_URL: "http://10.20.70.10"
      SHOW_DEBUG_LOG: "FALSE"
    restart: always
    networks:
      - wx
  service-influxdb:
    container_name: wx-svc-influxdb
    image: influxdb:2.7.0
    volumes:
      - ./services/influxdb/data:/var/lib/influxdb2:rw
    env_file:
      - .env
    entrypoint: ["./entrypoint.sh"]
    restart: always
    ports:
      - ${DOCKER_INFLUXDB_INIT_PORT}:${DOCKER_INFLUXDB_INIT_PORT}
    networks:
      - wx
  service-telegraf:
    container_name: wx-svc-telegraf
    image: telegraf:1.26.1
    volumes:
      - ${TELEGRAF_CFG_PATH}:/etc/telegraf/telegraf.conf:rw
    env_file:
      - .env
    restart: always
    depends_on:
      - service-influxdb
    networks:
      - wx
  grafana-dashboard:
    container_name: wx-svc-dashboard
    image: grafana/grafana-enterprise
    ports:
      - 3000:3000
    volumes:
      - ./services/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./services/grafana/data:/var/lib/grafana
    depends_on:
      - service-influxdb
    restart: always
    networks:
      - wx
networks:
  wx:
    name: wx
