apiVersion: v1
kind: PersistentVolume
metadata:
  name: service-telegraf-claim0
  labels: 
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 10.20.30.5
    path: "/data/nfs_share"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-dashboard-claim0
  labels: 
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 10.20.30.5
    path: "/data/nfs_share"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-1-claim0
  labels: 
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 10.20.30.5
    path: "/data/nfs_share"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-1-claim1
  labels: 
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 10.20.30.5
    path: "/data/nfs_share"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: service-influxdb-claim0
  labels: 
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 10.20.30.5
    path: "/data/nfs_share"